seq = 'abcccccaaaaaaaaa';
%seq = 'adcacdadadadadcacdadcadbabadcadcadadcadcadcacadcdcbadadadadcdcdcadabadadbadadabadcdadadadbadcadcdbadcadbadadcadcadadcdcadadcdcadbabadcacadcadadadcadbadabadcadcadacadbabacadcadadadcdcadcdcdadcacadcdcda';

phat = mle('discrete uniform', seq)